ALTER TABLE csgo ADD COLUMN index VARCHAR;
UPDATE csgo SET index = 'csgo' where index is NULL;
ALTER TABLE csgo ADD COLUMN genre VARCHAR;
UPDATE csgo SET genre = 'fps' where genre is NULL;
ALTER TABLE destiny2 ADD COLUMN index VARCHAR;
UPDATE destiny2 SET index = 'destiny2' where index is NULL;
ALTER TABLE destiny2 ADD COLUMN genre VARCHAR;
UPDATE destiny2 SET genre = 'fps' where genre is NULL;
ALTER TABLE fo4 ADD COLUMN index VARCHAR;
UPDATE fo4 SET index = 'fo4' where index is NULL;
ALTER TABLE fo4 ADD COLUMN genre VARCHAR;
UPDATE fo4 SET genre = 'fps' where genre is NULL;
ALTER TABLE gta5 ADD COLUMN index VARCHAR;
UPDATE gta5 SET index = 'gta5' where index is NULL;
ALTER TABLE gta5 ADD COLUMN genre VARCHAR;
UPDATE gta5 SET genre = 'fps' where genre is NULL;
ALTER TABLE pd2 ADD COLUMN index VARCHAR;
UPDATE pd2 SET index = 'pd2' where index is NULL;
ALTER TABLE pd2 ADD COLUMN genre VARCHAR;
UPDATE pd2 SET genre = 'fps' where genre is NULL;
ALTER TABLE pubg ADD COLUMN index VARCHAR;
UPDATE pubg SET index = 'pubg' where index is NULL;
ALTER TABLE pubg ADD COLUMN genre VARCHAR;
UPDATE pubg SET genre = 'fps' where genre is NULL;
ALTER TABLE r6siege ADD COLUMN index VARCHAR;
UPDATE r6siege SET index = 'r6siege' where index is NULL;
ALTER TABLE r6siege ADD COLUMN genre VARCHAR;
UPDATE r6siege SET genre = 'fps' where genre is NULL;
ALTER TABLE rust ADD COLUMN index VARCHAR;
UPDATE rust SET index = 'rust' where index is NULL;
ALTER TABLE rust ADD COLUMN genre VARCHAR;
UPDATE rust SET genre = 'fps' where genre is NULL;
ALTER TABLE tf2 ADD COLUMN index VARCHAR;
UPDATE tf2 SET index = 'tf2' where index is NULL;
ALTER TABLE tf2 ADD COLUMN genre VARCHAR;
UPDATE tf2 SET genre = 'fps' where genre is NULL;
ALTER TABLE warframe ADD COLUMN index VARCHAR;
UPDATE warframe SET index = 'warframe' where index is NULL;
ALTER TABLE warframe ADD COLUMN genre VARCHAR;
UPDATE warframe SET genre = 'fps' where genre is NULL;

ALTER TABLE celeste ADD COLUMN index VARCHAR;
UPDATE celeste SET index = 'celeste' where index is NULL;
ALTER TABLE celeste ADD COLUMN genre VARCHAR;
UPDATE celeste SET genre = 'platformer' where genre is NULL;
ALTER TABLE cuphead ADD COLUMN index VARCHAR;
UPDATE cuphead SET index = 'cuphead' where index is NULL;
ALTER TABLE cuphead ADD COLUMN genre VARCHAR;
UPDATE cuphead SET genre = 'platformer' where genre is NULL;
ALTER TABLE deadcells ADD COLUMN index VARCHAR;
UPDATE deadcells SET index = 'deadcells' where index is NULL;
ALTER TABLE deadcells ADD COLUMN genre VARCHAR;
UPDATE deadcells SET genre = 'platformer' where genre is NULL;
ALTER TABLE geometrydash ADD COLUMN index VARCHAR;
UPDATE geometrydash SET index = 'geometrydash' where index is NULL;
ALTER TABLE geometrydash ADD COLUMN genre VARCHAR;
UPDATE geometrydash SET genre = 'platformer' where genre is NULL;
ALTER TABLE gettingoverit ADD COLUMN index VARCHAR;
UPDATE gettingoverit SET index = 'gettingoverit' where index is NULL;
ALTER TABLE gettingoverit ADD COLUMN genre VARCHAR;
UPDATE gettingoverit SET genre = 'platformer' where genre is NULL;
ALTER TABLE gris ADD COLUMN index VARCHAR;
UPDATE gris SET index = 'gris' where index is NULL;
ALTER TABLE gris ADD COLUMN genre VARCHAR;
UPDATE gris SET genre = 'platformer' where genre is NULL;
ALTER TABLE hollowknight ADD COLUMN index VARCHAR;
UPDATE hollowknight SET index = 'hollowknight' where index is NULL;
ALTER TABLE hollowknight ADD COLUMN genre VARCHAR;
UPDATE hollowknight SET genre = 'platformer' where genre is NULL;
ALTER TABLE portal2 ADD COLUMN index VARCHAR;
UPDATE portal2 SET index = 'portal2' where index is NULL;
ALTER TABLE portal2 ADD COLUMN genre VARCHAR;
UPDATE portal2 SET genre = 'platformer' where genre is NULL;
ALTER TABLE terraria ADD COLUMN index VARCHAR;
UPDATE terraria SET index = 'terraria' where index is NULL;
ALTER TABLE terraria ADD COLUMN genre VARCHAR;
UPDATE terraria SET genre = 'platformer' where genre is NULL;
ALTER TABLE transformice ADD COLUMN index VARCHAR;
UPDATE transformice SET index = 'transformice' where index is NULL;
ALTER TABLE transformice ADD COLUMN genre VARCHAR;
UPDATE transformice SET genre = 'platformer' where genre is NULL;

ALTER TABLE ark ADD COLUMN index VARCHAR;
UPDATE ark SET index = 'ark' where index is NULL;
ALTER TABLE ark ADD COLUMN genre VARCHAR;
UPDATE ark SET genre = 'rpg' where genre is NULL;
ALTER TABLE bdo ADD COLUMN index VARCHAR;
UPDATE bdo SET index = 'bdo' where index is NULL;
ALTER TABLE bdo ADD COLUMN genre VARCHAR;
UPDATE bdo SET genre = 'rpg' where genre is NULL;
ALTER TABLE conan ADD COLUMN index VARCHAR;
UPDATE conan SET index = 'conan' where index is NULL;
ALTER TABLE conan ADD COLUMN genre VARCHAR;
UPDATE conan SET genre = 'rpg' where genre is NULL;
ALTER TABLE eso ADD COLUMN index VARCHAR;
UPDATE eso SET index = 'eso' where index is NULL;
ALTER TABLE eso ADD COLUMN genre VARCHAR;
UPDATE eso SET genre = 'rpg' where genre is NULL;
ALTER TABLE ffxiv ADD COLUMN index VARCHAR;
UPDATE ffxiv SET index = 'ffxiv' where index is NULL;
ALTER TABLE ffxiv ADD COLUMN genre VARCHAR;
UPDATE ffxiv SET genre = 'rpg' where genre is NULL;
ALTER TABLE mhw ADD COLUMN index VARCHAR;
UPDATE mhw SET index = 'mhw' where index is NULL;
ALTER TABLE mhw ADD COLUMN genre VARCHAR;
UPDATE mhw SET genre = 'rpg' where genre is NULL;
ALTER TABLE poe ADD COLUMN index VARCHAR;
UPDATE poe SET index = 'poe' where index is NULL;
ALTER TABLE poe ADD COLUMN genre VARCHAR;
UPDATE poe SET genre = 'rpg' where genre is NULL;
ALTER TABLE sevendtd ADD COLUMN index VARCHAR;
UPDATE sevendtd SET index = 'sevendtd' where index is NULL;
ALTER TABLE sevendtd ADD COLUMN genre VARCHAR;
UPDATE sevendtd SET genre = 'rpg' where genre is NULL;
ALTER TABLE skyrim ADD COLUMN index VARCHAR;
UPDATE skyrim SET index = 'skyrim' where index is NULL;
ALTER TABLE skyrim ADD COLUMN genre VARCHAR;
UPDATE skyrim SET genre = 'rpg' where genre is NULL;
ALTER TABLE witcher3 ADD COLUMN index VARCHAR;
UPDATE witcher3 SET index = 'witcher3' where index is NULL;
ALTER TABLE witcher3 ADD COLUMN genre VARCHAR;
UPDATE witcher3 SET genre = 'rpg' where genre is NULL;

ALTER TABLE assettocorsa ADD COLUMN index VARCHAR;
UPDATE assettocorsa SET index = 'assettocorsa' where index is NULL;
ALTER TABLE assettocorsa ADD COLUMN genre VARCHAR;
UPDATE assettocorsa SET genre = 'sports' where genre is NULL;
ALTER TABLE beatsaber ADD COLUMN index VARCHAR;
UPDATE beatsaber SET index = 'beatsaber' where index is NULL;
ALTER TABLE beatsaber ADD COLUMN genre VARCHAR;
UPDATE beatsaber SET genre = 'sports' where genre is NULL;
ALTER TABLE dirtrally ADD COLUMN index VARCHAR;
UPDATE dirtrally SET index = 'dirtrally' where index is NULL;
ALTER TABLE dirtrally ADD COLUMN genre VARCHAR;
UPDATE dirtrally SET genre = 'sports' where genre is NULL;
ALTER TABLE efootballpes2020 ADD COLUMN index VARCHAR;
UPDATE efootballpes2020 SET index = 'efootballpes2020' where index is NULL;
ALTER TABLE efootballpes2020 ADD COLUMN genre VARCHAR;
UPDATE efootballpes2020 SET genre = 'sports' where genre is NULL;
ALTER TABLE footballmanager2019 ADD COLUMN index VARCHAR;
UPDATE footballmanager2019 SET index = 'footballmanager2019' where index is NULL;
ALTER TABLE footballmanager2019 ADD COLUMN genre VARCHAR;
UPDATE footballmanager2019 SET genre = 'sports' where genre is NULL;
ALTER TABLE nba2k19 ADD COLUMN index VARCHAR;
UPDATE nba2k19 SET index = 'nba2k19' where index is NULL;
ALTER TABLE nba2k19 ADD COLUMN genre VARCHAR;
UPDATE nba2k19 SET genre = 'sports' where genre is NULL;
ALTER TABLE rocketleague ADD COLUMN index VARCHAR;
UPDATE rocketleague SET index = 'rocketleague' where index is NULL;
ALTER TABLE rocketleague ADD COLUMN genre VARCHAR;
UPDATE rocketleague SET genre = 'sports' where genre is NULL;
ALTER TABLE russianfishing4 ADD COLUMN index VARCHAR;
UPDATE russianfishing4 SET index = 'russianfishing4' where index is NULL;
ALTER TABLE russianfishing4 ADD COLUMN genre VARCHAR;
UPDATE russianfishing4 SET genre = 'sports' where genre is NULL;
ALTER TABLE steep ADD COLUMN index VARCHAR;
UPDATE steep SET index = 'steep' where index is NULL;
ALTER TABLE steep ADD COLUMN genre VARCHAR;
UPDATE steep SET genre = 'sports' where genre is NULL;
ALTER TABLE tekken7 ADD COLUMN index VARCHAR;
UPDATE tekken7 SET index = 'tekken7' where index is NULL;
ALTER TABLE tekken7 ADD COLUMN genre VARCHAR;
UPDATE tekken7 SET genre = 'sports' where genre is NULL;

ALTER TABLE civ6 ADD COLUMN index VARCHAR;
UPDATE civ6 SET index = 'civ6' where index is NULL;
ALTER TABLE civ6 ADD COLUMN genre VARCHAR;
UPDATE civ6 SET genre = 'strategy' where genre is NULL;
ALTER TABLE dota2 ADD COLUMN index VARCHAR;
UPDATE dota2 SET index = 'dota2' where index is NULL;
ALTER TABLE dota2 ADD COLUMN genre VARCHAR;
UPDATE dota2 SET genre = 'strategy' where genre is NULL;
ALTER TABLE factorio ADD COLUMN index VARCHAR;
UPDATE factorio SET index = 'factorio' where index is NULL;
ALTER TABLE factorio ADD COLUMN genre VARCHAR;
UPDATE factorio SET genre = 'strategy' where genre is NULL;
ALTER TABLE footballmanager2020 ADD COLUMN index VARCHAR;
UPDATE footballmanager2020 SET index = 'footballmanager2020' where index is NULL;
ALTER TABLE footballmanager2020 ADD COLUMN genre VARCHAR;
UPDATE footballmanager2020 SET genre = 'strategy' where genre is NULL;
ALTER TABLE heartsofiron ADD COLUMN index VARCHAR;
UPDATE heartsofiron SET index = 'heartsofiron' where index is NULL;
ALTER TABLE heartsofiron ADD COLUMN genre VARCHAR;
UPDATE heartsofiron SET genre = 'strategy' where genre is NULL;
ALTER TABLE raft ADD COLUMN index VARCHAR;
UPDATE raft SET index = 'raft' where index is NULL;
ALTER TABLE raft ADD COLUMN genre VARCHAR;
UPDATE raft SET genre = 'strategy' where genre is NULL;
ALTER TABLE rimworld ADD COLUMN index VARCHAR;
UPDATE rimworld SET index = 'rimworld' where index is NULL;
ALTER TABLE rimworld ADD COLUMN genre VARCHAR;
UPDATE rimworld SET genre = 'strategy' where genre is NULL;
ALTER TABLE smite ADD COLUMN index VARCHAR;
UPDATE smite SET index = 'smite' where index is NULL;
ALTER TABLE smite ADD COLUMN genre VARCHAR;
UPDATE smite SET genre = 'strategy' where genre is NULL;
ALTER TABLE warthunder ADD COLUMN index VARCHAR;
UPDATE warthunder SET index = 'warthunder' where index is NULL;
ALTER TABLE warthunder ADD COLUMN genre VARCHAR;
UPDATE warthunder SET genre = 'strategy' where genre is NULL;
ALTER TABLE totalwarwarhammer2 ADD COLUMN index VARCHAR;
UPDATE totalwarwarhammer2 SET index = 'totalwarwarhammer2' where index is NULL;
ALTER TABLE totalwarwarhammer2 ADD COLUMN genre VARCHAR;
UPDATE totalwarwarhammer2 SET genre = 'strategy' where genre is NULL;